''' You are familiar with different tricks of output. Here is the last one of concatenating the string. You have two strings and your task is to print the string after concatenating them.

Example:
Input: string1 = Geeks , string2 = Code
Output: GeeksCode
Explanation: Geeks and Code are two different strings. Output is generated by concatenating them using "+".   '''

def print_fun(string1, string2):
    print (string1 + string2)
